name: Java CI with Maven (QA Environment)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Create config.qa.properties file
        run: |
          mkdir -p src/main/resources
          echo "VALID_USERNAME=${{ secrets.VALID_USERNAME }}" >> src/main/resources/config.qa.properties
          echo "VALID_PASSWORD=${{ secrets.VALID_PASSWORD }}" >> src/main/resources/config.qa.properties
          echo "INVALID_PASSWORD=${{ secrets.INVALID_PASSWORD }}" >> src/main/resources/config.qa.properties
          echo "EMPTY_USERNAME=${{ secrets.EMPTY_USERNAME }}" >> src/main/resources/config.qa.properties
          echo "EMPTY_PASSWORD=${{ secrets.EMPTY_PASSWORD }}" >> src/main/resources/config.qa.properties

      - name: Build and Run Tests in QA Environment
        run: mvn clean install -Denv=qa
